export const ACTIONS = {
	OPEN_NEW_CARD_POPUP: "OPEN_NEW_CARD_POPUP",
	CLOSE_NEW_CARD_POPUP: "CLOSE_NEW_CARD_POPUP",
	SET_ONLY_ADDRESS: "SET_ONLY_ADDRESS",
	SET_USER_AND_ADDRESS: "SET_USER_AND_ADDRESS",
};
